### ISSUE TITLE
Question about C++ API Code License

### ISSUE THREAD

**Issue by redyoshi49q** [fullphat/snarl#12]
I've been thinking about incorporating Snarl support into the open source player [Clementine](https://github.com/clementine-player/Clementine).  It'd be nice to be able to use [the example code supplied in the Snarl repo](https://github.com/fullphat/snarl/tree/master/hdr/C%2B%2B) for that purpose as opposed to writing code that does the same thing from scratch, but it's not entirely clear to me if [the licensing terms of the example code](https://github.com/fullphat/snarl/blob/master/hdr/C%2B%2B/_License.txt) allow performing this incorporation (Clementine's licensed under GPL version 3 or later).

Was the license text "you can use [this code] in any way you see fit" intended to allow the relicensing of this code to other open source licenses such as GPLv3+?

**Comment by fullphat** [comment]
Hi

All of our example code is totally licence free.  You may re-use it or modify it as you see fit.  Furthermore, example code may be directly inserted into applications which use other open source licences or even closed source/proprietary ones.

Thanks

Chris
full phat products
__________________________
http://getsnarl.info
Twitter: @snarlhappens

**Comment by Reonekot** [comment]
It is ment as "use in any way you like", be it open or closed source,
commercial or not. I don't mean to make any restrictions on the license of
the software using this. (The license file is only there to say "don't
blame me for failures in the software".) If you think the file needs to say
otherwise for you to use it with GPLv3+ I'll see if I can change it.

**Comment by redyoshi49q** [comment]
I was more interested in making sure that the intended use of the code was in line with the authors' intentions (whether you clarify the license and how is up to you guys).  Thanks for the clarification.
