### ISSUE TITLE
Crashes on first launch

### ISSUE THREAD

**Issue by vavavr00m** [fullphat/snarl#16]
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: snarl.exe
  Application Version:  46.0.0.93
  Application Timestamp:    5648ecaa
  Fault Module Name:    StackHash_0a7b
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   00000000
  Exception Code:   c0000005
  Exception Offset: ffff4485
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1: 0a7b
  Additional Information 2: 0a7bcadba4afc08d3d6ab91a0dc929c2
  Additional Information 3: 5883
  Additional Information 4: 5883dc7b57b7d659e25a1aaee8b42218

**Comment by fullphat** [comment]
Can you run snarl.exe -debug and send me the log output from %APPDATA%\fullphat\snarl ?

Thanks! 

Chris
full phat products
__________________________
http://getsnarl.info
Twitter: @snarlhappens

**Comment by vavavr00m** [comment]
[snarl.log](https://github.com/fullphat/snarl/files/155698/snarl.log.txt)

**Comment by fullphat** [comment]
Seems to be an issue loading extensions.  I think there's a way to stop snarl starting extensions during startup but I can't remember it.  Try holding down left CTRL while it launches?

Chris
full phat products
__________________________
http://getsnarl.info
Twitter: @snarlhappens

**Comment by vavavr00m** [comment]
I'll try that. Note that it also doesn't start on windows login.

**Comment by fullphat** [comment]
Any luck?
