### ISSUE TITLE
Disable global settings hotkey

### ISSUE THREAD

**Issue by Reonekot** [fullphat/snarl#17]
It seems like Snarl registers a global hotkey for Ctrl+F10 for launching settings. I can't find where I can disable this? (Very annoying as I can't use Run To Cursor hotkey in Visual Studio.)

**Comment by fullphat** [comment]
Which version of snarl?

Chris
full phat products
__________________________
http://getsnarl.info
Twitter: @snarlhappens

**Comment by Reonekot** [comment]
4.0 beta 7

**Comment by fullphat** [comment]
As of R5.0 we no longer use a hotkey to launch settings.  We will trap certain Mod+Esc combos but that will be configurable (and off by default).
