### ISSUE TITLE
SNP/HTTP localhost only

### ISSUE THREAD

**Issue by Akrasia** [fullphat/snarl#31]
Can only reach SNP/HTTP restful api on localhost.

Is this intentional?

https://drive.google.com/file/d/0B-DXGrGCN6DCc0YwdHJYYWxxYWs/view?usp=sharing

**Comment by fullphat** [comment]
Which version of Snarl are you using?  But, yes, this is by design.  You need to add a URL ACL for Windows to allow listening on 0.0.0.0 (https://msdn.microsoft.com/en-us/library/windows/desktop/cc307223(v=vs.85).aspx)

**Comment by Akrasia** [comment]
Sorry I can not seem to make heads or tails of the documentation and what i may be doing wrong.
Google has no relevant results either.

I'm in windows 10 entering: 
`netsh http add urlacl url=http://localhost:9596/ user=DOMAIN\user listen=yes`

Any suggestions?

**Comment by fullphat** [comment]
Sorry!  Do this:

1. Launch an administrative Command Prompt
2. Run the following:

`netsh http add urlacl url=http://+:9596/ user=Everyone listen=yes`

Restart Snarl (or disable/enable the listener). 👍

**Comment by Akrasia** [comment]
Awesome! Works on my local network. Had to adjust iplisten with:
`netsh http add iplisten ipaddress=0.0.0.0`

But that may have been my fault trying to troubleshoot the issue.

Thanks for the help this will make it so much easier to finish my notification system.

**Comment by fullphat** [comment]
Woop! 😀
