### ISSUE TITLE
SNP/HTTP: Proper URL for local icons located on disk

### ISSUE THREAD

**Issue by Akrasia** [fullphat/snarl#33]
Can't seem to find any documentation on custom local images using SNP/HTTP.

I've tried:

`curl -s -X POST -H "Content-Type: application/json" "http://10.0.0.50:9597/v2/appsaccess_token=123456" -d "{ 'app-id': 'app', 'title': 'app' }", 'icon': 'file:///C:/directory/icon.png'`

and simply:

`curl -s -X POST -H "Content-Type: application/json" "http://10.0.0.50:9597/v2/appsaccess_token=123456" -d "{ 'app-id': 'app', 'title': 'app' }", 'icon': 'C:/directory/icon.png'`

I just get the default icon.

However http:// works for icons:

`curl -s -X POST -H "Content-Type: application/json" "http://10.0.0.50:9597/v2/appsaccess_token=123456" -d "{ 'app-id': 'app', 'title': 'app' }", 'icon': 'http://website/subdomain/icon.png'`

**Comment by fullphat** [comment]
This worked fine for me:

`curl -H "Content-Type: application/json" "http://192.168.1.10:8080/v2/notifications" -d '{ "title": "Hello, world", "icon": "c:/icons/home.png" }'`

Not sure if it's a cut-and-paste error, but the JSON looks to be wrong in those examples you've posted?

**Comment by Akrasia** [comment]
Oh whoops I did that when i commented out that section of code. I will try one more time when i get a chance and report back if it was user error on my end. Sorry.

**Comment by Akrasia** [comment]
Found the solution!
Forward slashes work while backslashes do not.

**Comment by Reonekot** [comment]
Normally backslashes should be escaped, have you tried that? (Ie. C:\\folder\\icon.png)

**Comment by Akrasia** [comment]
Yes escaping the backslashes works as well. I can't believe I overlooked that.
