### ISSUE TITLE
Snarl 5.0 beta 7: Error handling  GNTP Applications. 

### ISSUE THREAD

**Issue by iMelsom** [fullphat/snarl#62]
Sending a GNTP message to an unregistered app sucessfully register it as new app. Message content in GNTP message is decoded to another app name: 
Registered app: 
event: addclass?app-sig=local.protocol.gntp.Growl_IM&id=Growl_IM&name=Growl_IM

Register result: 
Notification.SendToOSD():Sending "notify?transport=win32&api=5&flags=18432&app-sig=application/x-vnd.fullphat-snarl&app-icon=G:\snarl r5.0-beta-7\snarl 5.0\etc\icons\snarl.png&app-name=Snarl&event-name=Other Notifications&guid=31688572-c1db-4d85-ae52-c1a6293a3d5c&token=416&title=New Application Registered&text="Growl IM" registered with Snarl&icon=C:\Users\xiame.OPM\AppData\Local\Temp\2250c694-4a2a-41f4-b57e-2c94141fbc38.png&priority=0&timeout=10&callback=sys:block:dbcb9b82-6b69-455c-bd9a-da05fef1251a&callback-label=Block"...
Notification.SendToOSD():OSD->SUCCESS

Message content: 
From listener: 
Listener.connectionHandler(): received: GNTP/1.0 NOTIFY NONE MD5:06BF4C73D1F26DFAB20087E72D711BC0.5C611CDA¬¬Application-Name: Growl IM¬¬Notification-Name: Growl_IM¬¬Notification-Title: Melding fra xiame ¬¬Notification-Text: BLIPP¬¬Melding sendt kl 14:57¬¬Notification-Priority: -2¬¬Notification-Sticky: True¬¬Notification-ID: Melding fra xiame 1548683836¬¬Notification-Callback-Context: CallbackRequested¬¬Notification-Callback-Context-Type: STRING¬¬Notification-Callback-Context-Target: http://intranett/dev/xiame/growlIM?NotificationID=Melding+fra+xiame+1548683836&NotificationContext=CallbackRequested¬¬Notification-Callback-Context-Target-Method: GET ¬¬Notification-Callback-Target: http://intranett/dev/xiame/growlIM?NotificationID=Melding+fra+xiame+1548683836&NotificationContext=CallbackRequested¬¬Notification-Callback-Target-Method: GET ¬¬¬¬¬¬

From GNTP decoder: 
Snarl.notify(): raw content is "notify?app-sig=gntp/Growl_IM/event-id=Growl_IM/title=Melding fra xiame /text=BLIPP

Searching for app: 
ApplicationRoster.Find(): app with signature 'gntp/Growl_IM' not found!

Result: 
Notification not shown. 

Sent GNTP message works with both GfW (Growl) and Snarl R3.1.

**Comment by iMelsom** [comment]
[snarl_5_debug.log](https://github.com/fullphat/snarl/files/2803303/snarl_5_debug.log)
Full log from Snarl 5.0 beta7 test

**Comment by fullphat** [comment]
Thanks!  Will look into this...

**Comment by fullphat** [comment]
This should now work fine in R5.1 Beta1; please test and report back 👍

**Comment by iMelsom** [comment]
GNTP notifications are now arriving and are shown. Thank you :)

**Comment by fullphat** [comment]
Many thanks for the feedback!
