### ISSUE TITLE
5.0.0 breaks Windows Notification for Snarl (v1.2.0.1)

### ISSUE THREAD

**Issue by snarl5bugs** [fullphat/snarl#64]
After installing Snarl 5.0.0 "Windows Notification for Snarl" is no longer able to successfully send
snarls when new balloon-tooltip appear (win7 x64).
Registration works ok, but after that the snarl server replies with -202, see the debug log of "Windows Notification for Snarl" below.

01-Mar-2019 14:01:11 ***Windows Notification for Snarl v1.2.0.1 Logging started***
01-Mar-2019 14:01:11 [i] Starting Windows Notification for snarl...
01-Mar-2019 14:01:11 [i]   ->Helper thread started {7608}
01-Mar-2019 14:01:11 [i]   ->Setting hook thread id {5468} instance {3915710464}
01-Mar-2019 14:01:11 [i]   ->Hook installed
01-Mar-2019 14:01:11 [i]   ->Application path: C:\Program Files (x86)\full phat\Snarl\tools\Windows_Notification_for_Snarl\x64\
01-Mar-2019 14:01:11 [i]   ->Settings path: C:\Users\[snip]\AppData\Roaming\full phat\snarl\WindowsNotification\
01-Mar-2019 14:01:11 [i]   ->Icon cache path: C:\Users\[snip]\AppData\Roaming\full phat\snarl\WindowsNotification\cache\
01-Mar-2019 14:01:11 [i]   ->Snarl icon path: Not Found
01-Mar-2019 14:01:11 [i]   ->Debug output: Yes, Log: Yes
01-Mar-2019 14:01:11 [i]   ->Use application icon: Yes
01-Mar-2019 14:01:11 [i]   ->Overlay application icon: No
01-Mar-2019 14:01:11 [i]   ->Use tray icon: No
01-Mar-2019 14:01:11 [i]   ->Single notification style: No
01-Mar-2019 14:01:11 [i] Already registered with Snarl {Status: 203}
01-Mar-2019 14:01:11 [i] Added callback {hWnd: 2754796, Message: 32769, hIcon: Yes}
01-Mar-2019 14:01:11 [i] Added callback {hWnd: 329790, Message: 1124, hIcon: Yes}
01-Mar-2019 14:01:11 [i] Added callback {hWnd: 1183884, Message: 2025, hIcon: Yes}
01-Mar-2019 14:01:11 [i] Added callback {hWnd: 66702, Message: 1225, hIcon: Yes}
01-Mar-2019 14:01:11 [i] Added callback {hWnd: 66794, Message: 1124, hIcon: Yes}
01-Mar-2019 14:01:11 [i] Added callback {hWnd: 132280, Message: 1120, hIcon: Yes}
01-Mar-2019 14:01:38 [!] Could not display notification {Snarl error code: -202}, forwarded notification to Windows default handler
01-Mar-2019 14:01:38 [i] Notification details:
01-Mar-2019 14:01:38 [i]   ->Title: Hello
01-Mar-2019 14:01:38 [i]   ->Info: This is a test...
01-Mar-2019 14:01:38 [i]   ->From: nircmd.exe
01-Mar-2019 14:01:47 [i] Deleted callback {hWnd: 1843494}

The same worked fine with all the 5.0 betas before.
Any ideas ?

Cheers !

**Comment by fullphat** [comment]
Hmm... I do seem to have messed something up here.  I'm working on it now but can you point me to v1.2.0.1 (or the latest version) of Windows Notification for Snarl?  I've only got an older version to hand.  Thanks!

**Comment by snarl5bugs** [comment]
The latest (to my knowledge) version 1.2.0.1 of "Windows Notification for Snarl" from 2014-05-15 can be found in a newsgroup discussion here:
https://groups.google.com/forum/?fromgroups#!topic/snarl-discuss/DZDZXzf_Ors
direct link:
https://groups.google.com/group/snarl-discuss/attach/a8d63564b80ce04/Windows_Notification_for_Snarl_v1.2.0.1.7z?part=0.1

Thanks for looking into the problem.

Cheers !

**Comment by fullphat** [comment]
Can you try R5.1 Beta 1 (see issue #65 for info) and let me know if this is now fixed?

**Comment by snarl5bugs** [comment]
Just tested with the new 5.1b1 and it indeed seems to be fixed.
Thanks a lot for that :1st_place_medal: !

One strange thing I immediately noticed with the new beta:
The global "Sticky notifications" setting had no effect at all.
I had to manually set "DefaultDuration": 0 in the settings json...

Cheers !

**Comment by fullphat** [comment]
Great stuff - I'll mark this as closed.  Would you mind opening a new issue for the global sticky bug?
