### ISSUE TITLE
replace-uid shouldn't destroy and re-create notifications

### ISSUE THREAD

**Issue by blackwind** [fullphat/snarl#7]
I've found that the Snarl API's merge-uid parameter performs an in-place modification of the provided uid (as one would expect), while the replace-uid parameter appears to destroy uid and create a new instance of it. I'd like to suggest replace-uid instead perform an in-place modification.

Use case: I'm replacing AudioMon with an EventGhost macro, and if you drag the Windows volume slider from 0 to 100, for example, there's a lot of flickering as the notification closes and reopens 100 times. As a workaround, I'm currently using merge-uid with the OS X style and no body text, but I strongly believe replace-uid should be modified so that this isn't necessary; after all, what's the point of the parameter at all if you can replicate its behavior by destroying and recreating the notification yourself?

**Comment by fullphat** [comment]
Try using "update-uid" - does that do what you want?

**Comment by blackwind** [comment]
The API I'm using doesn't currently support that because update-uid doesn't appear to be in any of the documentation, so, unsure at this time. If you add it to the documentation, I'll definitely pass word of it along to the API author.

**Comment by fullphat** [comment]
Sorry - I misled you.  Simply notify using the same uid and Snarl will update the notification.

Example:

notify?text=Hello&uid=123
notify?text=World!&uid=123

Should result in a notification displaying "hello" that then changes to "world".

**Comment by blackwind** [comment]
Seems to work. What's the use case, then, for replace-uid?

**Comment by fullphat** [comment]
In some cases it can be more appropriate, especially if the user's attention to the notification is required.

In testing we found that updating a notification can be missed by the user whereas the disappearance and re-appearance of a notification directs their attention back to it.

Some examples where replace-uid may be preferable:

DVD inserted then ejected
Caps Lock enabled then released
User has logged on/off to an IM service

**Comment by blackwind** [comment]
Makes sense. Thanks for the insight. :smiley:
