### ISSUE TITLE
Snarl OSD Ignoring Settings

### ISSUE THREAD

**Issue by LeeThompson** [fullphat/snarl#76]
Snarl 5.1 Beta 4 is ignoring OSD settings for font and placement etc.   No matter what it always does notifications on the upper left of the screen.

OS: Windows 10 Enterprise 1903

**Comment by LeeThompson** [comment]
OSD.rc
[osd.zip](https://github.com/fullphat/snarl/files/3651163/osd.zip)

**Comment by LeeThompson** [comment]
I'm going to try backing up my Snarl settings in %appdata% and then wiping them and re setting up stuff.

**Comment by fullphat** [comment]
Thanks Lee - yes, the new CarbonOSD is still considered experimental and doesn't support all the features the old one does.  I'll mark this as closed for now, but I will continue to add support for certain features, such as the default notification position.
