### ISSUE TITLE
Snarl found Sending via Win32... Failed:109

### ISSUE THREAD

**Issue by butgit** [fullphat/snarl#86]
I'm following the steps in [Snarl tutorial](http://snarl.fullphat.net/content/snarl-tutorial/)
First, I registered 'my test app' event:
`d:\...\snarl 5.0\tools\HeySnarl>heysnarl "register?app-sig=mytestapp&app-title=My Test App&keep-alive=1"`

Output:
```
Snarl found
Sending via Win32...
Ok
```
Then I added its class:
`d:\...\snarl 5.0\tools\HeySnarl>heysnarl "addclass?app-sig=mytestapp&id=1&name=Test Event&title=Test&text=My Event&icon=!system-warning"`

Output:
```
Snarl found
Sending via Win32...
Ok

```
So far, so good. But, when I do this:
`d:\...\snarl 5.0\tools\HeySnarl>heysnarl "notify?app-sig=mytestapp&id=1"`
I get the following error message:
```
Snarl found
Sending via Win32...
Failed:109
```

The following is my debug log.

-=-=- Snarl logging started -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
bootstrap: Thu, 26 Mar 2020 13:07:33 GMT
bootstrap: o/s info follows...
  platform: Win32NT
  version: Microsoft Windows NT 6.2.9200.0
  service pack: 
bootstrap: server info follows...
  release: 5.0
  api:     47
  sys:     47.120
  build:   5.0.0 (id=0)
bootstrap: getting sysadmin settings...
bootstrap: initialising settings...
EnvManager.loadAdminSettings(): no redirect.rc
EnvManager.loadAdminSettings(): trying from d:\med\portables\snarl 5.0\sysadmin.json...
EnvManager.getSettingsFromPathOrUrl(): "d:\med\portables\snarl 5.0\sysadmin.json" assumed to be a path...
Files.ReadTextFromPath(): failed to read from "d:\med\portables\snarl 5.0\sysadmin.json": Could not find file 'd:\med\portables\snarl 5.0\sysadmin.json'.
EnvManager.getSettingsFromPathOrUrl(): failed: null file retrieved
EnvManager.loadAdminSettings(): failed
StartService(): envmgr.service 5.1.0 started ok
bootstrap: starting UI...
bootstrap: checking user data folders...
bootstrap: %APPDATA% is "C:\Users\me2\AppData\Roaming\"
bootstrap: starting management server on '*:9989'...
bootstrap: didn't start: falling back to localhost...
bootstrap: management server started!
bootstrap: starting SnarlOSD...
bootstrap: starting notification roster...
NotificationRoster.Start(): %appdata% is C:\Users\me2\AppData\Roaming\full phat\snarl 5.0\etc\
NotificationRoster.Start(): loading osd.rc...
NotificationRoster.Start(): checking osd presets folder...
NotificationRoster.getOsdPresets(): loading osd presets...
bootstrap: starting application roster...
bootstrap: starting extension roster...
bootstrap: starting rules roster...
bootstrap: starting presence monitor...
bootstrap: starting Win32 IPC transport...
bootstrap: enabling...
bootstrap: displaying welcome message...
bootstrap: starting network roster...
NetworkRoster.Start(): loading custom transports...
NetworkRoster.Start(): loading listeners...
NetworkRoster.Start(): starting listeners...
NetworkRoster.Start(): loading subscriptions...
NetworkRoster.Start(): loading forwarders...
bootstrap: main startup completed, other threads may still be initialising...
Stopping presence monitor...
Removing tray icon...
Stopping network roster...
Stopping extension roster...
Stopping application roster...
Closing handling window...
Telling SnarlOSD to quit...
Stopping management server...
===== END =====

**Comment by fullphat** [comment]
Hi there!

Error 109 means a required argument is missing.  The notify command must have at least one of "title", "text" or "icon".

Try this:

`d:\...\snarl 5.0\tools\HeySnarl>heysnarl "notify?app-sig=mytestapp&id=1&title=Test"`

Does that fix it?

**Comment by butgit** [comment]
Yes, that fixed it. Thanks for your help.
